import { ProjectStoreContext } from "./types";

export const defaultTemplate: ProjectStoreContext = {
  id: "project_8a0cb87c",
  name: "Document Project V1",
  tabs: [
    {
      id: "template-1_b956f7f7",
      name: "New Template",
      projectId: "project_8a0cb87c",
      pages: [
        {
          name: "page",
          id: "page-1_f04d9f6b",
          tabId: "template-1_b956f7f7",
          elements: [
            {
              id: "container_88c840e5",
              type: "container",
              props: {
                layoutMode: "flex",
                direction: "column",
                gap: 0,
                padding: 16,
                backgroundColor: "transparent",
                fontFamily: "inherit",
                textAlign: "left",
                justifyContent: "flex-start",
                alignItems: "stretch",
                gridColumns: 3,
                justifyItems: "stretch",
                minHeight: 600,
                minHeightUnit: "px",
                width: 100,
                widthUnit: "%",
                heightUnit: "auto",
                alignSelf: "auto",
                justifySelf: "auto",
              },
              children: [
                {
                  id: "container_254430ad",
                  type: "container",
                  props: {
                    layoutMode: "flex",
                    direction: "row",
                    gap: 12,
                    padding: 16,
                    backgroundColor: "transparent",
                    fontFamily: "inherit",
                    textAlign: "left",
                    justifyContent: "space-between",
                    alignItems: "center",
                    gridColumns: 3,
                    justifyItems: "stretch",
                    minHeight: 80,
                    minHeightUnit: "px",
                    width: 100,
                    widthUnit: "%",
                    heightUnit: "auto",
                    alignSelf: "auto",
                    justifySelf: "auto",
                  },
                  children: [
                    {
                      id: "container_592afa78",
                      type: "container",
                      props: {
                        layoutMode: "flex",
                        direction: "row",
                        gap: 0,
                        padding: 0,
                        backgroundColor: "transparent",
                        fontFamily: "inherit",
                        textAlign: "left",
                        justifyContent: "flex-start",
                        alignItems: "center",
                        gridColumns: 3,
                        justifyItems: "stretch",
                        minHeight: 80,
                        minHeightUnit: "px",
                        width: 100,
                        widthUnit: "%",
                        heightUnit: "auto",
                        alignSelf: "auto",
                        justifySelf: "auto",
                      },
                      children: [
                        {
                          id: "container_4e4fcf60",
                          type: "container",
                          props: {
                            layoutMode: "flex",
                            direction: "column",
                            gap: 12,
                            padding: 16,
                            backgroundColor: "transparent",
                            fontFamily: "inherit",
                            textAlign: "left",
                            justifyContent: "flex-start",
                            alignItems: "stretch",
                            gridColumns: 3,
                            justifyItems: "stretch",
                            minHeight: 80,
                            minHeightUnit: "px",
                            width: 100,
                            widthUnit: "%",
                            heightUnit: "auto",
                            alignSelf: "auto",
                            justifySelf: "auto",
                          },
                          children: [
                            {
                              id: "image_d3e2b9e9",
                              type: "image",
                              props: {
                                src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80",
                                alt: "Placeholder image",
                                width: 100,
                                height: 40,
                                objectFit: "cover",
                                borderRadius: 8,
                                alignSelf: "auto",
                                justifySelf: "auto",
                              },
                            },
                          ],
                        },
                        {
                          id: "container_8ce608a9",
                          type: "container",
                          props: {
                            layoutMode: "flex",
                            direction: "column",
                            gap: 0,
                            padding: 12,
                            backgroundColor: "transparent",
                            fontFamily: "inherit",
                            textAlign: "left",
                            justifyContent: "flex-start",
                            alignItems: "stretch",
                            gridColumns: 3,
                            justifyItems: "stretch",
                            minHeight: 80,
                            minHeightUnit: "px",
                            width: 100,
                            widthUnit: "%",
                            heightUnit: "auto",
                            alignSelf: "auto",
                            justifySelf: "auto",
                          },
                          children: [
                            {
                              id: "text_1db06c29",
                              type: "text",
                              props: {
                                content: "Your Company",
                                alignSelf: "auto",
                                justifySelf: "auto",
                                fontSize: 20,
                                fontWeight: "bold",
                              },
                            },
                            {
                              id: "text_d585f65e",
                              type: "text",
                              props: {
                                content: "Better Documents, Better Business",
                                alignSelf: "auto",
                                justifySelf: "auto",
                              },
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "container_b893e74d",
                      type: "container",
                      props: {
                        layoutMode: "flex",
                        direction: "column",
                        gap: 12,
                        padding: 16,
                        backgroundColor: "transparent",
                        fontFamily: "inherit",
                        textAlign: "left",
                        justifyContent: "center",
                        alignItems: "center",
                        gridColumns: 3,
                        justifyItems: "stretch",
                        minHeight: 80,
                        minHeightUnit: "px",
                        width: 100,
                        widthUnit: "%",
                        heightUnit: "auto",
                        alignSelf: "auto",
                        justifySelf: "auto",
                      },
                      children: [
                        {
                          id: "text_ade0fcf8",
                          type: "text",
                          props: {
                            content: "VISUAL DOCUMENT",
                            alignSelf: "center",
                            justifySelf: "auto",
                            fontSize: 36,
                            fontWeight: "bold",
                          },
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "container_f687b40f",
                  type: "container",
                  props: {
                    layoutMode: "flex",
                    direction: "row",
                    gap: 12,
                    padding: 16,
                    backgroundColor: "transparent",
                    fontFamily: "inherit",
                    textAlign: "left",
                    justifyContent: "space-between",
                    alignItems: "center",
                    gridColumns: 3,
                    justifyItems: "stretch",
                    minHeight: 80,
                    minHeightUnit: "px",
                    width: 100,
                    widthUnit: "%",
                    heightUnit: "auto",
                    alignSelf: "auto",
                    justifySelf: "auto",
                  },
                  children: [
                    {
                      id: "container_be19e6fb",
                      type: "container",
                      props: {
                        layoutMode: "flex",
                        direction: "column",
                        gap: 0,
                        padding: 16,
                        backgroundColor: "transparent",
                        fontFamily: "inherit",
                        textAlign: "left",
                        justifyContent: "flex-start",
                        alignItems: "stretch",
                        gridColumns: 3,
                        justifyItems: "stretch",
                        minHeight: 80,
                        minHeightUnit: "px",
                        width: 100,
                        widthUnit: "%",
                        heightUnit: "auto",
                        alignSelf: "auto",
                        justifySelf: "auto",
                      },
                      children: [
                        {
                          id: "text_5077fd10",
                          type: "text",
                          props: {
                            content: "ISSUER/",
                            alignSelf: "auto",
                            justifySelf: "auto",
                            fontWeight: "bold",
                          },
                        },
                        {
                          id: "text_d51ebc35",
                          type: "text",
                          props: {
                            content: "Issuer Details",
                            alignSelf: "auto",
                            justifySelf: "auto",
                          },
                        },
                      ],
                    },
                    {
                      id: "container_ff4fb774",
                      type: "container",
                      props: {
                        layoutMode: "flex",
                        direction: "column",
                        gap: 12,
                        padding: 16,
                        backgroundColor: "transparent",
                        fontFamily: "inherit",
                        textAlign: "left",
                        justifyContent: "center",
                        alignItems: "center",
                        gridColumns: 3,
                        justifyItems: "stretch",
                        minHeight: 80,
                        minHeightUnit: "px",
                        width: 100,
                        widthUnit: "%",
                        heightUnit: "auto",
                        alignSelf: "auto",
                        justifySelf: "auto",
                      },
                      children: [
                        {
                          id: "text_d7020888",
                          type: "text",
                          props: {
                            content: "Client details",
                            alignSelf: "auto",
                            justifySelf: "auto",
                          },
                        },
                      ],
                    },
                    {
                      id: "container_a7b3ff4b",
                      type: "container",
                      props: {
                        layoutMode: "flex",
                        direction: "row",
                        gap: 12,
                        padding: 16,
                        backgroundColor: "transparent",
                        fontFamily: "inherit",
                        textAlign: "left",
                        justifyContent: "flex-start",
                        alignItems: "stretch",
                        gridColumns: 3,
                        justifyItems: "stretch",
                        minHeight: 80,
                        minHeightUnit: "px",
                        width: 100,
                        widthUnit: "%",
                        heightUnit: "auto",
                        alignSelf: "auto",
                        justifySelf: "auto",
                      },
                      children: [
                        {
                          id: "text_a627897f",
                          type: "text",
                          props: {
                            content: "No/Date: ",
                            alignSelf: "auto",
                            justifySelf: "auto",
                            fontWeight: "bold",
                          },
                        },
                        {
                          id: "text_1f8d4214",
                          type: "text",
                          props: {
                            content: "C-2026-0612026-09-04",
                            alignSelf: "auto",
                            justifySelf: "auto",
                          },
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  selectedTabId: "template-1_b956f7f7",
  selectedPageId: "page-1_f04d9f6b",
  selectedElmId: "container_88c840e5",
};
